services:
  nginx:
    image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/nginx
    build: ./nginx
    ports:
      - "80:8000"
    networks:
      - front-tier
    depends_on:
      - vote

  db:
    platform: linux/amd64
    image: postgres:15-alpine
    volumes:
      - ./healthchecks/postgres.sh:/healthchecks/postgres.sh
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
    healthcheck:
      test: ["CMD", "/healthchecks/postgres.sh"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    platform: linux/amd64
    image: redis
    volumes:
      - ./healthchecks/redis.sh:/healthchecks/redis.sh
    networks:
      - back-tier
    healthcheck:
      test: ["CMD", "/healthchecks/redis.sh"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 15s

  seeder:
    platform: linux/amd64
    image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/seed-data
    build: ./seed-data
    networks:
      - front-tier
    depends_on:
      - nginx

  vote:
    platform: linux/amd64
    image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/vote
    build: ./vote
    networks:
      - front-tier
      - back-tier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 15s
    depends_on:
      redis:
        condition: service_healthy

  result:
    platform: linux/amd64
    image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/result
    build: ./result
    ports:
      - "4000:4000"
    networks:
      - front-tier
      - back-tier
    depends_on:
      db:
        condition: service_healthy

  worker:
    platform: linux/amd64
    image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/worker
    build:
      context: ./worker
    networks:
      - back-tier
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
networks:
  front-tier:
  back-tier:

volumes:
  db-data:
