apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      name: internal
    - port: 80
      targetPort: 5000
      name: external
    - port: 8000
      targetPort: 5000
      name: for-seeder
  selector:
    pod_type: vote
