apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      pod_type: worker
  template:
    metadata:
      name: worker-replicaset
      labels:
        pod_type: worker
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/worker
          name: worker-pod
