apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      pod_type: redis
  template:
    metadata:
      name: redis-replicaset
      labels:
        pod_type: redis
    spec:
      volumes:
        - name: redis-healthcheck
          emptyDir: {}
      containers:
        - image: redis
          name: redis-pod
          volumeMounts:
            - mountPath: /healthchecks
              name: redis-healthcheck
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - "bash"
                - "/healthchecks/redis.sh"
            initialDelaySeconds: 15
            periodSeconds: 15
      initContainers:
        - name: init-redis-pod
          image: alpine
          command:
            [
              "sh",
              "-c",
              "apk update && apk add wget && wget -O /healthchecks/redis.sh https://gitlab.imt-atlantique.fr/login-nuage/healthchecks/-/raw/main/redis.sh?ref_type=heads && chmod +x /healthchecks/redis.sh",
            ]
          volumeMounts:
            - mountPath: /healthchecks
              name: redis-healthcheck
