- name: Génération du template PGPASS
  ansible.builtin.template:
    src: .pgpass.j2
    dest: /tmp/.pgpass
    owner: postgres
    group: postgres
    mode: '0600'
  become_user: root

- name: Requête de récupération du path du répertoire de données
  community.postgresql.postgresql_query:
    db: postgres
    query: SHOW data_directory
  register: data_directory_request_result

- name: Arrêt du service
  ansible.builtin.service:
    name: postgresql
    state: stopped
  become_user: root

- name: Suppression du répertoire de données
  ansible.builtin.file:
    path: "{{data_directory_request_result.query_result[0].data_directory}}"
    state: absent

# PAS BESOIN DU FAIT QUE LE COMMANDE DE REPLICATION CRÉRA AUTOMATIQUE LE REPERTOIRE SI IL MANQUANT (ET AVEC LES BONS DROIT)
# - name: Recréation du répertoire de données
#   ansible.builtin.file:
#     path: "{{data_directory_request_result.query_result[0].data_directory}}"
#     owner: postgres
#     group: postgres
#     mode: '0700'
#     state: directory

- name: Commande pour la Réplication
  ansible.builtin.shell: 
    cmd: PGPASSFILE=/tmp/.pgpass pg_basebackup -h {{pg_master_ip}} -U {{pg_replicator_username}} -p 5432 -D {{data_directory_request_result.query_result[0].data_directory}} -R --checkpoint=fast -w
    executable: /bin/bash

# J'AI L'IMPRESSION QUE LA SUPPRESSION DU .pgpass BLOQUE LA REPLICATION
# - name: Suppression du .pgpass
#   ansible.builtin.file:
#     path: /tmp/.pgpass
#     state: absent
#   notify: Restart postgres
