- hosts: all
  vars:
    pg_username: "postgres"
    pg_password: "postgres"
  roles:
    - role: pg_install

- hosts: postgres-primary.mathisplanchet.com
  roles:
    - role: pg_replication
  vars:
    pg_replicator_username: "replicator"
    pg_replicator_password: "replicator"
    pg_mode: "primary"
    pg_standby_ip: "postgres-standby.mathisplanchet.com"

- hosts: postgres-standby.mathisplanchet.com
  roles:
    - role: pg_replication
  vars:
    pg_replicator_username: "replicator"
    pg_replicator_password: "replicator"
    pg_mode: "standby"
    pg_standby_ip: "postgres-standby.mathisplanchet.com"
    pg_master_ip: "postgres-primary.mathisplanchet.com"
