apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: db-replica
spec:
  selector:
    matchLabels:
      pod_type: result
  template:
    metadata:
      name: result-replicaset
      labels:
        pod_type: result
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/login-k8s-1/voting-images/result
          name: result-pod
          ports:
            - containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 4000
